### ISSUE TITLE
Cannot create graph

### ISSUE THREAD

**Issue by Jasperswaagman** [jangaraj/Zabbix-Docker-Monitoring#12]
> Cannot create graph: graph with the same name "CPU utilization of foobar container" already exists.

Whenever a new container with the same name is discovered, it won't have the stacked graphs.

**Comment by zout** [comment]
Very annoying when you have some screens built the first time, and then they don't update anymore after a update to a container

**Comment by jangaraj** [comment]
That's how Low Level Discovery Works.

Quick win: Setup your docker discovery rule. Keep lost resources period (in days) = 0
https://www.zabbix.com/documentation/2.4/manual/discovery/low_level_discovery

Probably I'll provide some parameter for discovering - "use full docker ID instead of human name" and problem will be solved. Container ID will be always unique.

**Comment by Jasperswaagman** [comment]
Thanks for your quick reply and the quick win :) Ye I figured you could use the container ID for it, however that will take away the readability you have with the names.
